### ISSUE TITLE
how to enable toc

### ISSUE THREAD

**Issue by ddebby** [cherlas/hexo-theme-tranquilpeak#1]
Would you please make it clearily how to enable toc in the post page ?

**Comment by cherlas** [comment]
You just add `toc: true` in front matter, and insert `@[toc]` tag to where you want to show your post's toc.
I updated the README, please look at [it](https://github.com/cherlas/hexo-theme-tranquilpeak#目录). 
sorry for my english...😕

**Comment by ddebby** [comment]
Got it.  Thanks.
